### ISSUE TITLE
[BUG] Wrong arxiv link

### ISSUE THREAD

**Issue by kingsj0405** [DY112/LSMI-dataset#1]
Hi, dong young.
I'm very impressed by your amazing work, LSMI.
It seems your link to arxiv is wrong.

![image](https://user-images.githubusercontent.com/13496612/128976632-1bc52fe5-b594-42a2-9ca9-2668834fe2ab.png)

I hope it will be fixed soon.
Take care :)

**Comment by DY112** [comment]
I think you know the reason of that. 😁
Since our camera-ready version paper is not completed yet, the link that you click will not work until the mid-august.
By the way, I think that I heard your name before... Do we know each other?
