### ISSUE TITLE
Sony dataset 

### ISSUE THREAD

**Issue by Rafique-tech** [DY112/LSMI-dataset#11]
Hi,

I am using Sony dataset for my task at hand.
I'm following your provided code. I have query related to mixture map part where you are defining camera and RAW_EXT (for saturation). I have done modification in CAMERA variable with path (D:/Sony). For RAW_EXT am I supposed to use CAMERA.dng file (provided on GitHub "sony.dng") or I have to replace that with "CAMERA.arw".

In later case I'm getting error "input/out error".

**Comment by DY112** [comment]
For 0_cvt2tiff.py, you need to change the extension to arw, nef, etc. as appropriate, and for 1_make_mixture map, you don't need to change the extension because it uses dng.
