### ISSUE TITLE
The blacklevel confusion of  Sony sensor & Missed saturation clipping after wb

### ISSUE THREAD

**Issue by shuwei666** [DY112/LSMI-dataset#12]
I found the black level of Sony from the **.arw** raw file, which is $512$.
However, it seems that your code (in 2_pre_process_data.py)is using another manual value, which is $128$.

![image](https://github.com/DY112/LSMI-dataset/assets/106613332/dcbbd553-599f-485b-8940-8c2b75b9d1da)

Could you explain this discreprancy?

Thanks!

**Comment by shuwei666** [comment]
Thanks Dongyoung!

In addition, I noticed that your code may have a slight mistake when performing black level correction. It appears that you did not apply saturation clipping after white balancing, resulting in the issue of bright pink colors, as shown below. Since the multi-illu estimation is pixel-based, this oversight could potentially impact the final performance.

- your code without saturation clipping
![image](https://github.com/DY112/LSMI-dataset/assets/106613332/482e7e1e-6e91-4d47-a559-d4cf03818985)

- after saturation clipping

![image](https://github.com/DY112/LSMI-dataset/assets/106613332/a0cb4fe8-dc76-44ba-8ae6-1bb034aa6cf4)

and here is the added code:
> img_wb = img / illum_map
                img_wb = img_wb.clip(0, SATURATION)



Furthermore, I observed that your code in '2_pre_process_data.py' **only masks the Macbeth chart in the training dataset**, but not in the *validation* and *test* datasets. This could lead to unfair comparisons with other methods. For example, using a simple max-RGB method may also yield good results.

Anyway, thanks for your great work in this multi-illu estimation field. I am just hoping this minor tips could help make it better!

**Comment by DY112** [comment]
I appreciate your attention to detail.
However, if you trained the network with an unclipped dataset, you could simply clip the output of the network to a known white_level value as you did in your example.
If we train the network using the clipped image as GT, as you say, then we should be able to use the network output as is.

For color chart masking, I understand that some classical algorithms can take advantage from color charts and the comparison may not be fair.
However, if we are only comparing models based on deep learning, the assumption is that they are trained on training data, and the color chart is not visible during training, so in this case, masking only the training data should be fine.

I will add the caveats about saturation clipping and color chart masking to the README.

Thanks again!

**Comment by DY112** [comment]
Hi again @shuwei666 ,
I tried to visualize sony raw data with simple code, and I found why I set exceptional black level (128) for sony datas at that time. I'm not sure why exactly, but when I run the simple visualization code below that applies black level subtraction, white balance, and gamma correction, a black level of 128 produces the correct result, while using 512 produces a green-biased result as shown below.

- Black level 512
![blacklevel_512](https://github.com/DY112/LSMI-dataset/assets/24367643/8fdf2206-2074-4027-9790-7e7ff8384964)

- Black level 128
![blacklevel_128](https://github.com/DY112/LSMI-dataset/assets/24367643/0e8c11cc-189a-4061-8fe8-ab8167917757)

- Visualization code
```python
import rawpy, os, cv2
import numpy as np

raw = rawpy.imread('Place208_1.arw')
tiff_file = 'Place208_1.tiff'

white_level = raw.white_level
black_level = raw.black_level_per_channel[0]
wb_kernel = raw.camera_whitebalance
wb_kernel = (np.array(wb_kernel) / wb_kernel[1])[0:3]

raw_data = cv2.imread(tiff_file, cv2.IMREAD_UNCHANGED).astype(float)

black_subtracted = np.clip(raw_data - black_level, 0, white_level-black_level)

white_balanced = black_subtracted * wb_kernel[None, None, :]
white_balanced = np.clip(white_balanced, 0, white_level)
auto_bright = white_balanced / white_balanced.max()

gamma_corrected = np.power(auto_bright, 1/2.2)

print('White level: ', white_level)
print('Black level: ', black_level)
print('White balance kernel: ', wb_kernel)
print("Raw data min/max: ", raw_data.min(), raw_data.max())
print("Black subtracted min/max: ", black_subtracted.min(), black_subtracted.max())
print("White balanced min/max: ", white_balanced.min(), white_balanced.max())

# resize to 1/4
gamma_corrected = cv2.resize(gamma_corrected, (0,0), fx=0.25, fy=0.25)
cv2.imwrite('Place208_1.png', (gamma_corrected*255).astype(np.uint8))
```

At the time, and still today, I couldn't find the exact reason, but I remembered that using a black level of 128 was for the same reason as above.

Please let me know if you notice any discrepancies between the 512 black level in the Sony metadata and the results in the visualization above, or if there's something I'm missing.

**Comment by shuwei666** [comment]
Hi again,

This Sony sensor seems a bit odd. I noticed it is a 14-bit depth sensor, but if that's the case, its black level should be closer to 512. However, according to your analysis, 128 is what allows for correct image output, which suggests that you might have used a **12-bit mode** for saving. In other words, the effective bit depth of this Sony sensor's RAW data is actually 12 bits, right?

**Comment by DY112** [comment]
I don't know what is a 12-bit saving mode. Is it a mode of DCRAW? or Sony camera?
As I explained in the last answer, the RAW data (values from arw file) is a 14 bit data, but after we convert arw to tiff using DCRAW, the tiff data became 12-bit data. (1/4 scaled)

**Comment by shuwei666** [comment]
You can check the mode If you have the Sony alpha 9 camera.

It seems that the Sony Alpha 9 camera is operating in a 12-bit depth mode since the black level at 128 and saturation point at 4095 correspond to a 12-bit range. Another possibility is that the camera might not truly possess the 14-bit depth capability as advertised. A histogram analysis of the camera's raw output reveals that pixel values are predominantly within the lower range, up to approximately 50 (50 * 64 = 3200~4095). Conversely, there are significantly fewer occurrences of higher values. This pattern suggests that the actual effective bit-depth achieved by the camera is closer to 12-bit, contrary to the claimed 14-bit.

That's may the reason why you tried blacklevel as 512 but failed!
Bingo!
