### ISSUE TITLE
HDRNet

### ISSUE THREAD

**Issue by Corafeng** [DY112/LSMI-dataset#17]
hello, can you release the code of HDRNet training under this dataset?

**Comment by DY112** [comment]
Hi, @Corafeng, I used this repo :  https://github.com/creotiv/hdrnet-pytorch

**Comment by Corafeng** [comment]
Can you release the model parameters for HDRNet training

**Comment by DY112** [comment]
Sorry, we don't have it.
I think you can easily use the repo that I mentioned, using our dataloader code.
