### ISSUE TITLE
json files for nikon and sony subsets

### ISSUE THREAD

**Issue by birdortyedi** [DY112/LSMI-dataset#7]
Could you please share JSON files for nikon and sony subsets separately from RAW data zips? Especially the one for metadata, namely "meta.json". 

We could extract the RAW data without downloading z01 and z02 files by using some unzipping tricks, however, it does not produce JSON files for the metadata. This leads to some issues in preparing mixture maps.

We do not have storage space for downloading all of them at that time. So, if you have any chance to share JSON files for nikon and sony subsets, we would be very happy!

**Comment by DY112** [comment]
Hi @birdortyedi !
I uploaded meta.json and split.json files separately on the dataset directory (for galaxy,sony,nikon).
Thank you for your interest about our dataset. 😁
Happy new year!
